default: &default
  adapter: postgresql
  encoding: unicode
  # host: db
  username: postgres
  password: password

development:
  <<: *default
  database: vehicle_management_development

test:
  <<: *default
  database: vehicle_management_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
